### ISSUE TITLE
Design Doc

### ISSUE THREAD

**Issue by laixintao** [laixintao/mydumper2s3#1]
# Mysql2s3

## Background

Mydumper (https://github.com/maxbube/mydumper) 是一个 MySQL 全量备份工具，不支持将备份直接写到对象存储系统上，这个工具可以支持直接将 MySQL 的全量备份上传到 S3 上。

## Feature

- 可以只占用很小的空间就完成备份的上传，比如磁盘只有1G，可以备份一共100G的数据库；

### 1. Unix pipe

考虑到磁盘空间占用的问题，一个很直觉的方案是直接使用 Unix pipe 将 MyDumper 的 stdout 和 S3 上传的命令行连接起来。可以直接完成操作。`mydumper | s3cli <target>`。（之前在博客分享过如何在不占用磁盘空间的情况下备份 mysql https://www.kawabangga.com/posts/3416 ）

但是遗憾的是，mydumper 并不支持将 SQL dump 到 stdout，只支持输出到文件。（https://github.com/maxbube/mydumper/issues/24 ）

看了一下 mydumper 项目，在 Readme 中提到的 4 个 main feature：Parallelism, Easier to manage output, Consistency, Manageability. 在我看来，最重要的是 Parallelism，（猜想）Mydumper 为了性能，采用了多线程同时写入多个文件的方式，并不支持输出到 stdout，在不修改 Mydumper 的代码的情况下，直接使用 Unix pipe 是不可行的。

但是如果不使用 Mydumper，使用 mysqldump 是可以的。

![image](https://user-images.githubusercontent.com/9675939/93285457-71725800-f807-11ea-87cc-a966812e759b.png)

另外，在测试使用 mysqldump dump 到本地磁盘的时候，速度可以达到 70M。在上传S3的速度没有达到70Mib/s的情况下使用 Mydumper 加速 dump 是没有意义的。

### 2. 将S3挂载到系统上作为一个 Filesystem

使用 https://github.com/s3fs-fuse/s3fs-fuse 可以将 S3 作为 Linux 的一个 Filesystem。这样完全不需要本地磁盘，也无需自己做分片的逻辑。并且 s3fs 对大文件的上传也做了一些优化，速度可能会比在代码中直接使用 HTTP 上传更快一些。

Cons：

- 尚未验证 s3fs 的POSIX API是否能完全满足 Mydumper；

### 3. 黑魔法，使用 `LD_PRELOAD` 直接覆盖 `write_data`

看了下 mydumper 的源代码，只有3k+行 clang，考虑可以使用 `ld_preload` 直接将他的 `write_data` （以及打开文件相关的操作）直接覆盖（考虑使用golang，比较好些），将实现直接替换成写 s3。

这样相当于不需要本地磁盘就可以上传了。

参考：https://jvns.ca/blog/2014/11/27/ld-preload-is-super-fun-and-easy/

### 4. 一边 dump 一边上传

在 mydumper dump 数据的同时，直接读取已经写入文件的部分，然后上传到  s3。
当：
- mudumper 导出到这个文件已经完成，并且关闭文件；
- mysql2s3 将这个文件已经上传到 s3 并且 hash 校验一致；

就将这个文件删除，空间释放。

使用这个方案必须满足以下两个条件之一：
- 本地的磁盘空间足够大，可以允许dump下来所有的数据；
- 本地的磁盘文件不足够存放所有的数据，但是 s3 上传的速度大于 dump 的速度；

否则，mydumper 在dump到磁盘不足的时候会直接 crash。

在第二种情况下，推荐开启 mydumper 的 `--compress` 进行压缩，这样减轻上传的压力，也变慢了导出的速度。

**Comment by laixintao** [comment]
这个 issue 提到，磁盘满的时候 CPU 占用 100%，io hang，但是没有报错：
https://github.com/maxbube/mydumper/issues/40

**Comment by laixintao** [comment]
使用 watchdog + inotify 的方案监听文件的创建和关闭，实现 dump 结束就开始上传，放弃。

1. inotify 只能在 Linux 系统工作；
2. 实现太复杂，需要3个线程，监听创建 + 监听关闭 + 上传线程，这些线程之间需要通讯；
3. 一些临时文件会被上传，比如 `metadata.partial`

所以改成直接使用 interval check 的方式，只要文件存在并且没有被 mydumper 打开，就认为是上传就绪的状态。然后保存 last modified time，后面用于对比判断是否需要覆盖上传（理论上不会有这种情况）。

**Comment by davidducos** [comment]
Hi @laixintao , you might need to consider: https://github.com/maxbube/mydumper/milestone/9 as it is using stream similar to what you propose in: `4. Upload while dumping`. We don't support S3 upload yet, which might be good to have or we might decide to other tool do it.

**Comment by laixintao** [comment]
Hi @davidducos thanks!

the idea is that once mysqldumper dumped a file, I updated it to s3 immediately then delete it, so that we can to backup using a const space, instead of needing enough disk space that can hold all database dump files.

I suppose you mean: https://github.com/maxbube/mydumper/issues/100#issuecomment-919112608 ? I checked it, it was very awesome! I think we can have some tool (even writing one should be easy) read from stdout and backup what it reads right?

But one must understand the stdout format to read it correctly right? like read `\n-- ` then filename, then file content? (from the code https://github.com/maxbube/mydumper/pull/403/files#diff-cbe9fe4cf09b8b682353854e3a52bef5d0c3fc2fc178ee015617ba7db333ddccR707 ) 

I am looking forward to its release!
